describe("validate", () => {
  it.todo("should return an error when token is not provided")
  it.todo("should return an error when token is invalid")
  it.todo("should return an error when name is not provided")
  it.todo("should return an error when name is invalid")
  it.todo("should return an error when age is not provided")
  it.todo("should return an error when age is invalid")
  it.todo("should return an error when talker is provided but not with correct fields")
  it.todo("should return an error when taker is provided with invalid watchedAt date ")
  it.todo("should return an error when taker is provided with invalid rate ")
})